/*
 * This file was generated automatically by xsubpp version 1.9507 from the
 * contents of UnixAuth.xs. Do not edit this file, edit UnixAuth.xs instead.
 *
 *      ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "UnixAuth.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/uio.h>
#include "cmessage.h"

#line 19 "UnixAuth.c"
#ifdef __cplusplus
extern "C"
#endif
XS(boot_UnixAuth)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

    XSRETURN_YES;
}
